name: Weekly Summarization and Website Deployment

on:
  schedule:
    - cron: '18 6 * * *'  # Schedule to run at 9:15 PM UTC
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt  # Adjust as needed based on your project's requirements

      - name: Install PyTorch
        run: |
          pip install torch

      - name: Install TensorFlow
        run: |
          pip install tensorflow
      
      - name: Install Keras
        run: |
          pip install keras
          pip install --upgrade git+https://github.com/huggingface/transformers.git

      - name: Run summarization script
        run: python news_summarization.py

      - name: Install Render CLI, Verify Installation, and Set Environment Variables
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -sSL "$deploy_url" | sh
          render --version
          export RENDER_PROJECT_ID=srv-ckdhc5sgonuc73c0c3a0
          export RENDER_SERVICE_ID=ckdhc5sgonuc73c0c3a0
      
      - name: Get Latest MP3
        run: |
          cd generated_audios
          latest_mp3=$(ls -t *.mp3 | head -1)
          echo "Latest MP3 file: $latest_mp3"

      - name: Deploy Most Recent MP3 to Render
        run: |
          render set --project $RENDER_PROJECT_ID --service $RENDER_SERVICE_ID
          render up -f "$latest_mp3"

      - name: Download Latest Audio
        run: |
          python get_newest_audio.py

      - name: Deploy Website to Render
        run: |
          render set --project $RENDER_PROJECT_ID --service $RENDER_SERVICE_ID      
          cd web_page
          render up